### ISSUE TITLE
Unable to bring up the keyboard

### ISSUE THREAD

**Issue by darshanrampatel** [MicrosoftEdge/WebAppsDocs#21]
Having tried this with the same CodePen example (http://codepen.io/seksenov/pen/wBbVyb/?editors=101)), the keyboard does not appear automatically when pressing in the CodePen.

I am using a Windows 10 tablet with a touchscreen - is there a way to force this to open?

**Comment by seksenov** [comment]
Hi @darshanrampatel this was a known issue that has been fixed with the latest Windows 10 release build # 10586.
