### ISSUE TITLE
404 link to 'convert your website...'

### ISSUE THREAD

**Issue by JimGaleForce** [MicrosoftEdge/WebAppsDocs#42]
This page: 
https://microsoftedge.github.io/WebAppsDocs/en-US/win10/HWAfeatures.htm

has this text:
NOTE: If you are using a different development environment than Visual Studio 2015, you can download the Windows Standalone SDK for Windows 10 installer. 2. Follow the steps to **convert your website into an web app on Windows 10**.

which links to:
https://microsoftedge.github.io/WebAppsDocs/en-US/CreateHWA.md

which doesn't exist.

**Comment by mattwojo** [comment]
Thanks for filing this issue @JimGaleForce and our apologizes for the bad link. This page has recently been deprecated and replaced by: https://msdn.microsoft.com/en-us/windows/uwp/porting/hwa-create-windows  You will find the correct link to the Windows 10 Standalone SDK Installer there. 

(And we will have redirects set up for these pages soon)
